### ISSUE TITLE
🗣️ Interviews Efficiency

### ISSUE THREAD

**Issue by guibzo** [rocketmta/saturn#3]
## Modelo atual
Atualmente no servidor temos um modelo para o sistema de entrevistas que não é **muito eficiente** ou **agradável** nem para os jogadores nem para os oradores.

No momento, o funcionamento é que os oradores durante o **período do dia de domingo inteiro** vão liberando seus horários individualmente, com vagas para a **semana toda**. Os jogadores, com base nisso, agendam suas entrevistas.
Isso tem uma eficácia comprovadamente baixa e é muito **inconveniente**.

Os oradores precisam agendar seus horários tendo em mente como vai ser sua rotina e sua programação para a semana inteira, coisa que é basicamente impossível já que **imprevistos** podem acontecer a qualquer momento.
Os jogadores também assumem um compromisso que muitas vezes não se lembram, não podem assumir por conta de algum contratempo ou que simplesmente perdem o interesse devido à espera.

## Proposta
Acho que seria interessante um **modelo mais eficiente, interativo e direto** de tratar essa filtragem dos jogadores no servidor.
Acredito que um sistema de **pronta execução** através da plataforma seja infinitamente mais adequado e alinhado com as necessidades do servidor.

Funcionaria mais ou menos assim:
O jogador acessaria a plataforma em alguma aba **voltada para as entrevistas**.
O jogador então poderia entrar em uma **sala de espera** para ser entrevistado.
Os oradores conforme sua **disponibilidade imediata** e partindo dos **requisitos** estipulados internamente na equipe de suporte, fariam as entrevistas através da plataforma diretamente.
O orador em questão não escolheria o jogador a ser entrevistado e tão pouco puxaria um jogador pelo mérito posição na fila, mas sim através de algum **sistema aleatório** para puxar um jogador qualquer que estava na sala espera.
Quando o orador puxar esse jogador, eles teriam acesso à um chat de voz/texto para fazerem todo o processo da entrevista.

## Benefícios
Isso traria muitos benefícios, como:
- Aumentar e MUITO a **eficiência da filtragem**, já que muitas vezes os jogadores não aparecem na entrevista ou o orador fica impossibilitado;
- O jogador teria uma forma **mais direta e menos compromissada** de fazer a entrevista, já que não teria que marcar com dias de antecedência e tão pouco ficar ligado no chat/plataforma para ver se já há vagas disponíveis;
- A **padronização** seria infinitamente melhor, já que essa aba da plataforma poderia ser integrada diretamente com um painel com as questões da entrevista, a whitelist do jogador, o set do resultado da filtragem, etc;
- Poderia ser um método eficiente de aplicar uma **bonificação** para jogadores **Colaboradores, Premiums** e afins nesse processo, já que é possível definir que eles poderiam ter uma **% maior** de chance de caírem no sistema de randomizer da sala de espera (pense como se fosse um número da loteria, quem aposta em 2 números tem teoricamente a chance em dobro de ganhar);
- Dentre outros.

## Considerações
Sei que atualmente temos **recursos limitados** em questão de desenvolvimento.
Também sei que a **padronização** de um sistema como esse daria uma **identidade de qualidade** maior ainda para o ecossistema do projeto.
Porém, tal como outros sistemas e ideias internas aqui já comentadas, de **primeiro momento** isso poderia ser feito de uma forma com que funcione e que com o tempo vá sendo aprimorada.
Mas botando em questão **prioridades** aqui, não acho que a padronização da plataforma ou de um sistema desse porte (logo **inicialmente**) seja mais importante que a **necessidade** de ter mais  jogadores entrevistados e qualificados para desempenhar o RP de acordo com o que o servidor propõe **o quanto antes**.

Tendo em mente isso, todo esse processo que citei acima poderia ser **realizado inicialmente** através do Discord, que já possui a maioria dessas funcionalidades e tem fácil integração com algumas outras, e quando for possível de fato ser desenvolvido todo esse sistema na plataforma principal do servidor.
(Lembrando que o sistema de entrevistas atual já é feito através do Discord).

Como o que citei aqui não envolve somente a organização e a estrutura do suporte mas também a da plataforma, resolvi postar em formato de issue diretamente no saturn. Imagino que seja mais adequado que abrir esse tópico no Discord.

![Screenshot_11](https://github.com/rocketmta/saturn/assets/119091492/4cc13a52-66f9-4015-8c9d-82e150c12cf2)

**Comment by 777brn** [comment]
Primeiramente peço desculpas pela demora de uma resposta. Como te informei, estava (ainda continuo) bastante ocupado.

Em se tratando do primeiro ponto, sim, durante conversas com você concordei diversas vezes que o modelo que temos hoje em dia não é tão eficiente quanto deveria ser, e que quando foi desenvolvido, não foram levados em consideração os problemas que temos atualmente.
Sobre os horários, ainda pensando nesse modelo atual, também já dissemos que implementaríamos a opção do orador inserir seus horários não somente no domingo, mas também durante a semana, (pelo menos uns 3 dias — 
segunda, quarta e sexta por exemplo) por conta dos imprevistos que podem acontecer e acontecem.

Já sobre sua proposta, também discutimos que seria muito melhor em termos de eficiência, organização e satisfação de ambas as partes: tanto os oradores quanto os entrevistados seriam melhor beneficiados com este modelo em questão.
Também concordo com seu ponto de que a padronização não seja mais importante que a necessidade de termos um grande número de jogadores entrevistados para movimentarem a cidade de início. Só que mais coisas precisam ser discutidas num futuro breve: não seria melhor ter a opção do jogador entrar numa sala de espera **somente** quando tiver um orador disponível? Seria bom o orador liberar uma quantidade de vagas limitadas (de sua preferência) nestas salas de espera visando seu tempo livre para entrevistar e a perda de tempo dos jogadores que talvez não seriam entrevistados por exceder esse tempo livre? Como ficaria a questão da prioridade dos membros com cargos prioritários? Teríamos oradores somente para esses membros? Porque pensando na sugestão que deu (sei que é apenas uma ideia), não seria tão interessante um membro ter pago por um benefício que no final é incerto, que apenas lhe dá mais chances de ser entrevistado primeiro, levando em conta que isso só acontece uma vez então deveria ser "melhor aproveitado".

Bom, para concluir... são coisas mínimas e que serão discutidas num futuro breve. Continuo ocupado fazendo diversas coisas, e às vezes quando sobra um tempo livre não estou com cabeça para debater isso, mas garanto que vamos terminar essa discussão o quanto antes e aplicar alterações para deixar as entrevistas da melhor forma possível.

Mais uma vez te agradeço pelo empenho, reconhecemos seu esforço!

**Comment by guibzo** [comment]
## Considerando principalmente a **escalabilidade** do projeto:

> "*não seria melhor ter a opção do jogador entrar numa sala de espera somente quando tiver um orador disponível?*"
- R: Não, isso vai contra a proposta de tornar as coisas práticas. Não é necessário restringir a sala apenas para que os jogadores possam entrar quando houver um orador disponível; apenas indicar se há um orador ativo na sala de entrevistas já resolveria esse possível problema.

> "*Seria bom o orador liberar uma quantidade de vagas limitadas (de sua preferência) nestas salas de espera visando seu tempo livre para entrevistar e a perda de tempo dos jogadores que talvez não seriam entrevistados por exceder esse tempo livre?*"
- R: Também não. Adotar essa abordagem seria pegar o modelo atual (que não é prático) e aplicá-lo de uma forma diferente. Isso vai totalmente contra a proposta, especialmente considerando os imprevistos e a necessidade de praticidade no processo.

> "*Como ficaria a questão da prioridade dos membros com cargos prioritários?*"
- R: Sim, essa é uma vantagem para os apoiadores do projeto. No entanto, na proposta que mencionei, eles ainda teriam uma vantagem significativa em relação aos outros players, com o dobro de chances na fila. Além disso, seria mais fácil gerenciar essa prioridade quando pensamos em escalabilidade.
 - Até agora, considerando todos os cargos de apoio, temos um total de 407 apoiadores. Isso é com o servidor desligado e pouco movimentado. Até o momento, concluímos 555 entrevistas ao longo de vários meses. Agora, projete isso pra um ano no futuro: se o número de apoiadores por exemplo triplicar, seria viável manter uma fila EXCLUSIVA e única pra todos esses apoiadores manterem essa vantagem de exclusividade na entrevista?
 - Além de que é importante considerar se, no futuro, essa prioridade nas entrevistas continuará sendo uma das principais vantagens do programa de apoiador ou se se tornará apenas uma parte menor de um pacote maior de benefícios.
 

## Existem outras formas de aplicar tudo isso que resolveriam o problema inicial, como por exemplo:
1. Tenho em mente que vou ter tempo pra fazer ao menos 4 entrevistas **agora**.
2. Abro uma call no Discord com **2 vagas**. Somente players com cargo de apoiador podem entrar.
3. Quando esses 2 entram, aumento o limite da sala de 2 pra 4 e abro pra todos os players.
4. Assim, os players apoiadores teriam ainda o benefício.
5. O contra disso é que, por mais que bem improvável, ainda é possível nesse meio tempo de acontecer imprevisto e um desses 4 players que entraram na call tendo como certo a entrevista não conseguir ser entrevistado no momento. Isso pode ser resolvido manualmente contatando a pessoa e etc. Outro contra é que isso seria um processo mais manual inicialmente, mas ainda sim nada problemático.

Das duas formas resolveriam o problema que existe; na primeira proposta seria algo mais aberto, previsível e dando maiores chances pros players enquanto no segundo seria mais controlado e voltado pra dar maior exclusividade aos apoiadores.
Considerando que tudo seria feito no Discord inicialmente, acho que a abordagem mais controlada poderia ser mais funcional e organizada. No futuro com a adição do processo na plataforma, as ideias de ambas poderiam ser aproveitadas de uma melhor forma.


### Fato é que é necessário otimizar os recursos disponíveis. Isso também traria mais experiência sobre como aplicar coisas parecidas em outros campos do servidor em sistemas futuros de uma forma mais sustentável e prática.

**Comment by 777brn** [comment]
Perfeitamente esclarecido. Esse ato de simplesmente abrir uma call sem limite é o que me preocuparia, porque seria incerto que todos os jogadores ali presente seriam entrevistados.
Tenho um documento bem extenso que trata do suporte na plataforma, depois revejo o que tinha escrito e vejo se conseguimos aproveitar alguma ideia de lá também.
