### ISSUE TITLE
Whitelist Filter Query

### ISSUE THREAD

**Issue by guibzo** [rocketmta/saturn#4]
Na atualização do console, estou tendo alguns problemas em relação à paginação das whitelists.

Pra paginação funcionar de acordo com o filtro, preciso enviar os filtros checkeds como parâmetro na chamada de requisição da API pra que a API retorne os itens já filtrados de acordo.
Sem isso, os itens são buscados de acordo com a paginação mas nunca em número constante:

![image](https://github.com/rocketmta/saturn/assets/119091492/e559b1db-686a-4fe7-8ed8-50895bfb7bd8)

Call:
![image](https://github.com/rocketmta/saturn/assets/119091492/8737d1a1-9337-4708-994a-c71ab9f2002c)

Necessito que a API capte a query de "status" e retorne os itens baseado nisso e nas demais querys.

**Comment by guibzo** [comment]
Seria também interessante que o back-end retorne o total de itens baseado no status.
reprovedWhitelists - 3300
approvedWhitelists - 2352
interviewApprovedUsers - 555
interviewReprovedUsers - 333
...

Isso evitaria de fazer chamadas pra API e filtragens adicionais no front somente pra contabilizar o total de itens baseado no status, o que é necessário pra lógica do Metacritic e pra definição de quantas páginas têm a tabela.

**Comment by vitordvr** [comment]
Se eu entendi corretamente, você não precisa buscar essas informações diretamente na rota de pesquisa, mas sim na rota de análises. De qualquer forma, eu adicionei interviewApprovedUsers e interviewReprovedUsers, que você mencionou em: [a83c426](https://github.com/rocketmta/saturn/commit/a83c4260b66f6cf87922851b9a3d374366c9d9bb).

Exemplo de query:
```apache
https://saturn-api.rocketmta.com/saturn/player/whitelist/search?page=1&per_page=5&status=REPROVADO
```
