### ISSUE TITLE
Implementação de Mecanismo de Timeout para Rotas de Criação de Posts

### ISSUE THREAD

**Issue by felipesdotdev** [rocketmta/saturn#5]
Prezada equipe de desenvolvimento,

Espero que esta mensagem os encontre bem. Venho destacar um aspecto crucial da infraestrutura atual do sistema relacionado às operações de [criação,](https://saturn-api.rocketmta.com/v1/social/timeline/posts/create) [recuperação](https://saturn-api.rocketmta.com/v1/social/timeline/posts/engineFeedSearch) e [exclusão](https://saturn-api.rocketmta.com/v1/social/timeline/posts/delete) de posts. Após uma investigação detalhada, observei que as rotas CRUD existentes para posts necessitam de um mecanismo de timeout robusto. Essa ausência expõe uma vulnerabilidade, permitindo a automação potencial desses processos, levando a uma carga indevida no banco de dados.

Como programador, compreendo a importância primordial de incorporar medidas abrangentes de segurança em um sistema. A falta de controles adequados de timeout não apenas abre a porta para atividades automatizadas, mas também representa um sério risco de sobrecarga do banco de dados.

Solicito gentilmente a consideração e implementação de um mecanismo de timeout eficaz para todas as operações relacionadas à criação de posts, incluindo as rotas GET, POST e DELETE.

Agradeço pela atenção dedicada a este assunto. Se houver necessidade de esclarecimentos adicionais ou assistência, estou à disposição.

**Comment by vitordvr** [comment]
Boa noite @TryLooney, tudo bem? Agradecemos pelo seu tempo e paciência ao colaborar com o projeto.

Dado o estado em que a equipe e o projeto se encontravam no início, nós não acreditávamos em uma necessidade real de barramento/limitação. Felizmente e orgulhosamente, hoje isso não é mais uma realidade, e sua issue caiu como uma luva para esta adição. Revisei a passagem das rotas que interagem diretamente com o banco de dados e criei um novo middleware que assegura que requisições tenham um limite, bem como as devidas atualizações necessárias no frontend. LGTM!
