### ISSUE TITLE
Deletando posts de outros usuários e Modificando o perfil do usuário de maneira indevida

### ISSUE THREAD

**Issue by felipesdotdev** [rocketmta/saturn#7]
Deve estar chato ver eu aqui, mas to desocupado ultimamente.

**Deletando posts de outros usuários (https://saturn-api.rocketmta.com/v1/social/timeline/posts/delete)**
```json
{
	"postId": "e88b3428-573e-4bd8-aaf2-c3feff98da32"
}
```
Independente de qual usuário seja, com o postId correto posso deletar qualquer post.
*Recomendo uma validação de permissão*

---

**Colocando Gifs sem ter Premium (https://saturn-api.rocketmta.com/v1/social/profiles/images?avatar=true)**
Qualquer imagem é válida na rota(incluindo gifs), caso colocado de maneira correta na propriedade `image`.

*Recomendo uma validação de tipo de imagem seguido da permissão do usuário*

---

**Retirando nome de exibição(nickname) (https://saturn-api.rocketmta.com/v1/social/profiles?action=update:social)**
```json
{
	"nickname": "",
	"region_city": "",
	"region_country": "",
	"region_uf": "",
	"slug": "",
	"status": ""
}
```

Colocando apenas o slug já é possível a requisição.
*Recomendo uma validação do nickname não apenas no frontend*

**Comment by vitordvr** [comment]
Não, não é chato vê-lo aqui. Valorizamos muito a contribuição de qualquer pessoa, seja criando coisas, jogando ou relatando problemas/inconsistências. Nosso GitHub é um espaço para isso, sinta-se à vontade.
