### ISSUE TITLE
Funcionalidade no bot Ryder

### ISSUE THREAD

**Issue by guibzo** [rocketmta/saturn#8]
## Enhancement

Atualmente no suporte do servidor quando corrigimos as whitelists dos jogadores enviamos em uma sala do Discord privado da equipe o @ do usuário que corrigimos e indicamos o resultado adicionando um emoji.
Esse processo consome um tempo desnecessário e diminui a eficiência das correções.

A ideia é bem simples: Fazer com que o bot Ryder (que já trata dos eventos da entrevista) envie uma mensagem no chat de #wl-log contendo o @ do staff, @ do usuário, resultado da sua correção e, a data/hora no momento do envio. 
O bot daria um trigger nesse processo toda vez que o "status" de um usuário mudar, ou seja, além das correções da WL escrita também inclui resultados como o set do cargo de Entrevistado/Reprovado Entrevista.

![image](https://github.com/rocketmta/saturn/assets/119091492/13141864-2978-4e76-82ca-079b38f177cf)

**Comment by vitordvr** [comment]
Isso é feito apenas para evitar que outro membro da equipe leia a mesma whitelist ao mesmo tempo. A intenção é que, no futuro, ou mesmo em sua versão em nextjs, seja implementada uma funcionalidade que bloqueie outros membros da equipe de acessar uma whitelist que já está aberta em outro navegador. No entanto, como isso não está nos planos imediatos, a ideia atual permanece, como explicado anteriormente.
